USE `cs 338 project`;

SELECT `AREA NAME`
FROM AREADIST_TABLE
GROUP BY `AREA NAME`
ORDER BY COUNT(*) DESC
Limit 1;

SELECT MAX(`LAT`) AS LAT, MIN(`LON`) AS LON
FROM AREADIST_TABLE
WHERE `AREA NAME` = (SELECT `AREA NAME`
FROM AREADIST_TABLE
GROUP BY `AREA NAME`
ORDER BY COUNT(*) DESC
Limit 1);
