USE `cs 338 project`;

CREATE TABLE AREADIST_TABLE (
    DR_NO VARCHAR(15) PRIMARY KEY,
    Area INT NOT NULL,
    Area_Name VARCHAR(50) NOT NULL,
    Rpt_Dist_No INT NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    Cross_Street VARCHAR(255),
    LAT DECIMAL(9,6) UNIQUE NOT NULL,
    LON DECIMAL(9,6) UNIQUE NOT NULL
);

CREATE TABLE DATETIME_TABLE (
    OODR_NO VARCHAR(15) PRIMARY KEY,
    Date_Rptd DATETIME,
    Date_Occ DATETIME NOT NULL,
    Time_Occ INT NOT NULL,
    FOREIGN KEY (OODR_NO) REFERENCES AREADIST_TABLE(DR_NO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE STATUS_TABLE (
    SADR_NO VARCHAR(15) PRIMARY KEY,
    Status_now VARCHAR(2) NOT NULL,
    Status_Desc VARCHAR(50) NOT NULL,
    FOREIGN KEY (SADR_NO) REFERENCES AREADIST_TABLE(DR_NO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TYPE_TABLE (
    TIDR_NO VARCHAR(15) PRIMARY KEY,
    Crm_Cd INT UNIQUE NOT NULL,
    Crm_Cd_Desc VARCHAR(255) NOT NULL,
	FOREIGN KEY (TIDR_NO) REFERENCES AREADIST_TABLE(DR_NO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE VICTIM (
    VADR_NO VARCHAR(15) PRIMARY KEY NOT NULL,
    Vict_Age INT NOT NULL,
    Vict_Sex VARCHAR(2) NOT NULL,
    Vict_Descent VARCHAR(2),
    FOREIGN KEY (VADR_NO) REFERENCES AREADIST_TABLE(DR_NO) ON DELETE CASCADE ON UPDATE CASCADE
);